### ISSUE TITLE
Is there any way to get length of MappedRows?

### ISSUE THREAD

**Issue by 0x79756b69** [rusqlite/rusqlite#1007]
Hi! I'm new at this crate. This crate is very helpful ❤️ 

Is there any way to get length of `MappedRows`? or fetch one column.

If I'm missing any document, tell me.

Thanks!

**Comment by gwenn** [comment]
Number of rows ? No because rows are fetched lazily.
Number of columns ? Currently no but we can make `MappedRows` implements `AsRef<Statement>` to fix this.

**Comment by 0x79756b69** [comment]
I meant number of rows. Ok, I see.

I wish there was a feature like this.

https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-fetchone.html

**Comment by thomcc** [comment]
That's just `.next()` on one of the iterators. For example, see line 40 here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3b7a7f0898f98a34a76c8a74a72c8cfb

(This example is long, but mostly because I just copypasted it from the example in the README, and am too lazy to clean it up)

**Comment by 0x79756b69** [comment]
Oh, I see. Thanks for support.
