### ISSUE TITLE
rusqlite 0.26.2 adds MSRV requirement of 1.56; breaks compatibility

### ISSUE THREAD

**Issue by nmathewson** [rusqlite/rusqlite#1056]
With rusqlite 0.26.2, rusqlite now seems to require Rust 1.56, because of its use of `edition = "2021"` in its Cargo.toml.  Previously, rusqlite built fine with earlier versions of Rust.

And since rusqlite 0.26.0 and rusqlite 0.26.1 have been yanked, this means that any projects that previously used 0.26.x now have to decide whether to remain on a yanked version (undesirable), or upgrade their own MSRV to 1.56.

As best I can tell, rusqlite is not currently using anything from the 2021 edition of Rust.  Would it be possible to revert b41bb8085cdc92e43788b87a4c22bd1b4a370223 and go back to the 2018 edition?

**Comment by thomcc** [comment]
Yeah, give me until later today to do this, though.

**Comment by thomcc** [comment]
Thanks for the heads up, sorry for the trouble.

**Comment by nmathewson** [comment]
No worries; stuff happens! Thanks for the fast response.

**Comment by thomcc** [comment]
Fix published in https://crates.io/crates/rusqlite/0.26.3. Sorry about that again, cheers.

**Comment by nmathewson** [comment]
Thanks for the fast response!

**Comment by stephank** [comment]
For some reason, the crates.io version of libsqlite3-sys 0.23.2 still has `resolver = "2"` in its Cargo.toml, but I can't find that anywhere in git history. Not sure why or when it magically inserts that, but that puts msrv at 1.51.0. It looks like rusqlite 0.26.3 is fine, though.

I guess 1.51.0 is already over half a year old, which is a cut-off I've seen other projects make. I'm not sure if you have a intended msrv for this project?

I have a project that currently targets 1.46.0, but it's not 'stuck' on that version for any technical reason, so I can raise it. Thinking the 'half a year old' rule sounds okay.

**Comment by thomcc** [comment]
FWIW the half a year old rule is what tokio uses for its "5 year stability" promise: https://tokio.rs/blog/2020-12-tokio-1-0.

If it's not a problem for you, my self-serving answer is that you should update. The less self-serving answer is that because of the recent headaches here (which are our fault), I'd probably cut another release of libsqlite3-sys if there were indication that it would fix something (which... maybe???).

Anyway, there's no real MSRV in this project beyond "stable" (and trying not to break it outside of major releases — but that's largely because we do them frequently). I should be keeping a better eye on it (and will in the future — I just missed this one because we didn't really intend to have a minor release), but in practice I maintain rusqlite in my spare time, and find worrying about it too much to be painful/annoying.

That said, we have in the past accepted patches to make things work in older rusts, and in principal would again if the patch were small (particularly if it's not something we want to revert right away) or their reasoning compelling enough (such as "please help me get my rusqlite-using program into `$some_distro_pkg_repository`")

That said, again, this is somewhat of a special case, so I'm down to do another release of the -sys crate, but I'm not sure what the issue is, or if this would help.

P.S. If it's any consolation: 1.51 is easily the best release of rust in recent memory — const generics are game-changing.
