### ISSUE TITLE
Plans for async?

### ISSUE THREAD

**Issue by Aurora2500** [rusqlite/rusqlite#1075]
SQLite has [asynchronous capabilities](https://www.sqlite.org/asyncvfs.html), so I was wondering if there are any plans on implementing
 async to this crate.

I'd be willing to try and give it a go when I get to have free time.

**Comment by thomcc** [comment]
So, you don't want to use that. The sqlite3async code has *long* been abandoned.

Actually, I'm surprised there's no notice on that file, since if you take a look at [ext/async](https://github.com/sqlite/sqlite/tree/master/ext/async) (the final resting place of the asyncvfs), you can see this notice at the start of the README (which otherwise contains essentially the same text as your link, so you can be sure it's referring to the same thing):

> NOTE (2012-11-29):
>
> The functionality implemented by this extension has been superseded
> by WAL-mode.  This module is no longer supported or maintained.  The
> code is retained for historical reference only.

Anyway, not that it matters, but you're also a little confused about what this did back when it still was usable — it didn't make SQLite's APIs asynchronous, or add new APIs for async usage[^1]. It just let SQLite use asynchronous I/O under the hood.

So... even if you took the 9 year old abandonment notice as a challenge, and wanted to experiment with it, it wouldn't really change the situation for rusqlite's async story.

That said, it's a reasonable mistake to make, I thought the same thing when I came across it the first time.

[^1]: Well, beyond some stuff for use by custom VFSes which opt-in to async, I guess.

**Comment by thomcc** [comment]
Anyway, I think I'm going to close this since I would be against taking a patch that added anything based on that code.

I still am interested in improving the async usage story though. In the meantime, using a spawn_blocking or a background thread are the most straightforward options, sadly.
