### ISSUE TITLE
How to enable SQLITE_ENABLE_UPDATE_DELETE_LIMIT compilation flag

### ISSUE THREAD

**Issue by mbuczko** [rusqlite/rusqlite#1111]
Hey, what's the preferred way of enabling `SQLITE_ENABLE_UPDATE_DELETE_LIMIT` compilation flag (https://sqlite.org/compile.html#enable_update_delete_limit) if I wanted to get extended syntax for `UPDATE` operation?

I use sqlx which adds `libsqlite3-sys` as dependency so, I guess, the first step would be to enable `bundled` feature to have `LIBSQLITE_FLAGS` honored, right?
```toml
[dependencies.libsqlite3-sys]
version = "*"
features = ["bundled"]
```
I struggle though with the second step - how to actually pass the flag down to the compilation process. 
Thanks in advance for any hints.

**Comment by thomcc** [comment]
> Because of this, this option may only be used when the library is built from source, not from the amalgamation or from the collection of pre-packaged C files provided for non-Unix like platforms on the website. 

That's annoying. This means there's no way with libsqlite3-sys while using the bundled feature (most flags can be set either by `env LIBSQLITE3_FLAGS="-DFOO_BAR"`, but this one is not that way). Instead, you have to build a custom and use a custom version of sqlite, and tell us to link with it, however you can't use the normal method of building a custom SQLite, and need to build the custom amalgam to.

This is... a major pain in the ass to do manually. so I guess they don't care about this feature, or don't want you using it. (Note that in https://www.sqlite.org/amalgamation.html they recommend you just use the amalgamation).

So, I would encourage you to find a workaround for your use of this feature. Can you work around it with a subquery? E.g. instead of `DELETE FROM table WHERE $condition LIMIT 1000`, something like `DELETE FROM table WHERE id IN (SELECT id FROM table WHERE $condition LIMIT 1000)`? Probably a `WITH` expression (aka common table expression) should be able to do it too, in a similar way.

## Linking with custom amalgam

If you must build it, the steps will be slightly different on each OS, but will largely look like this (good luck, and I'm sorry):

- Download the SQLite sources from https://www.sqlite.org/download.html. You need the one described as "the complete (raw) source tree" under "Alternative Source Code Formats". (Currently https://www.sqlite.org/2022/sqlite-src-3370200.zip)
- Follow https://www.sqlite.org/howtocompile.html#building_the_amalgamation to build the amalgam. See also https://www.sqlite.org/amalgamation.html.  This is the step where `SQLITE_ENABLE_UPDATE_DELETE_LIMIT` must be set.
	- The output of that step will be a `sqlite3.h` and `sqlite3.c` file (the two parts of the amalgam).

- Compile the `sqlite3.c` you just made into a static library file (`libsqlite3.a` on unix, something else on windows that shouldn't end in `dll`). Put this in some folder, which we'll refer to as "/path/to/native/library/"
    - There are a number of defines you may want to set on the bundle, see <https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/build.rs#L109-L129> (and the rest of that function somewhat) what we use, which may be more than you need, it's up to you. I don't know if SQLITE_ENABLE_UPDATE_DELETE_LIMIT still needs to be set here, but it can't hurt.

- There are a few ways to proceed here, but the way that is simplest and most likely to work is the following: Add a `.cargo/config.toml` file (this is different than your Cargo.toml: https://doc.rust-lang.org/cargo/reference/config.html). See the section on build script override.

    ```toml
    [target.x86_64-unknown-linux-gnu.sqlite3]
    rustc-link-lib = ["static=sqlite3"]
    rustc-link-search = ["/path/to/folder/containing/native/library/"]
	rustc-flags = ["-L", "/path/to/folder/containing/native/library"]
	```

	Note that this will not work for installation via crates.io, and (like most of this) means you need to do specila work for each target.

- If this fails, you can also try passing `SQLITE3_LIB_DIR=/path/to/folder/containing/native/library` and `SQLITE3_STATIC=1` in the environment when building. Depending on Things, you may also need to set `SQLITE3_INCLUDE_DIR=/path/to/folder/containing/amalgam-header`. You will probably also need to disable the `libsqlite3-sys/bundled` feature, and enable the `libsqlite3-sys/bundled_bindings` feature.

This is a real pain in the ass, as you can tell, and honestly I think you should try to work around it by adjusting your query. Honestly, I've sort of skimmed over some parts of this. Feel free to come to the rusqlite discord (linked in the readme) and ask if you actually intend to go this route, but I would not recommend it.

**Comment by mbuczko** [comment]
Thank you for so detailed answer :)
> Can you work around it with a subquery? E.g. instead of DELETE FROM table WHERE $condition LIMIT 1000, something like DELETE FROM table WHERE id IN (SELECT id FROM table WHERE $condition LIMIT 1000)

Yup, this is exactly the way I composed the query before. I hoped that switching on additional syntax would be a no-brainer and could simplify these nested queries a bit. But well... it's definitely not a blocker and I learned at least a bit about amalgamations :) 

I'm closing this ticket as potential solution seems to be overly complicated. Thanks again for your time!
