### ISSUE TITLE
Consider using `Into<RowIndex>` instead of `I: RowIndex` in `Row::get` definition

### ISSUE THREAD

**Issue by delight-aug** [rusqlite/rusqlite#1118]
Hi! In the definition of the `Row::get` method, you're using two generics — one for the return type and one as an argument.
```
pub fn get<I: RowIndex, T: FromSql>(&self, idx: I) -> Result<T>
```

And then you have implemented `RowIndex` trait for `usize` and `&'_ str`.

This makes me specify both generics when constructing JSON with `json!` macro, even tho one of them is obvious.
```
|row| {
    Ok(json! {{
        "id": row.get::<usize, u64>(0)?,
        "category_id": row.get::<usize, u64>(1)?,
        "title": row.get::<usize, String>(2)?,
        "image": row.get::<usize, String>(3)?,
    }})
}
```
As a solution, you probably could define a `struct RowIndex` instead of the trait and then implement `From<usize>` and `From<&'_ str>` for it. Then specify `Into<RowIndex>` as an argument in a method.
```
pub fn get<T: FromSql>(&self, idx: Into<RowIndex>) -> Result<T>
```

So it will be possible to write:
```
|row| {
    Ok(json! {{
        "id": row.get::<u64>(0)?,
        "category_id": row.get::<u64>(1)?,
        "title": row.get::<String>(2)?,
        "image": row.get::<String>(3)?,
    }})
}

**Comment by gwenn** [comment]
Both [postgres](https://docs.rs/postgres/latest/postgres/row/trait.RowIndex.html) and [sqlx](https://docs.rs/sqlx/0.5.10/sqlx/trait.ColumnIndex.html) do the same...
And you can use `row.get::<_, ...>(0)` instead.
```sh
% rg -c 'get::<_,'
src/statement.rs:8
src/types/mod.rs:40
...
```

**Comment by thomcc** [comment]
Your suggestion as written would not solve the issue you describe, sadly. That is: `Into<RowIndex>` isn't a type, it's a trait, and so it can't be used in argument that way.

There are two possible ways to address that problem, either by moving the proposed `Into<RowIndex>` into a generic parameter (which leaves us in the same situation we're currently in, so it doesn't help) or by using `impl trait` instead (e.g. `idx: impl Into<RowIndex>`), which looks like what you want, but actually completely prevents use of turbofish on the function at all, which is definitely even worse.

I will note, in case you didnt realize: its probably nicer to force rust to infer the rowindex by filling the rowindex type with `_`. That is, `row.get::<_, String>(3)` can be done instead of `row.get::<usize, String>(3)`, which IMO is more convenient.

---
 
All that said, I would like to improve this someday, but it requires language features we don't have yet (but that have had a few discussions). Long term, there have been a few discussions from the Rust language team about a change to how argument-position impl-trait works, to allow turbofish for only the set of parameters declared as generics, but not for ones declared as impl trait.

That is, if it is added, we'd be able to specify this as

```rs
pub fn get<T: FromSql>(&self, idx: impl RowIndex) -> Result<T>
```

and then users would be allowed to turbofish this as `row.get::<String>(3)`. There would be no way to explicitly specify both generics, but I don't think that would be useful. That said, at the moment, this hasn't been implemented, and might require an RFC.

**Comment by delight-aug** [comment]
Thank both of you for the detailed responses, I didn't think of `_` at the time.
> That is: Into<RowIndex> isn't a type, it's a trait, and so it can't be used in argument that way.

My bad, haven't noticed that, was too sleepy. My apologies for wasting your time.
