### ISSUE TITLE
ETA for a new version of rusqlite?

### ISSUE THREAD

**Issue by huitseeker** [rusqlite/rusqlite#1242]
This would allow releasing a version of rusqlite depending on  
https://github.com/rusqlite/rusqlite/pull/1207
Which contains the first SQLite version containing the fix to [CVE-2022-35737](https://nvd.nist.gov/vuln/detail/CVE-2022-35737).

More details on the vulnerability:
https://blog.trailofbits.com/2022/10/25/sqlite-vulnerability-july-2022-library-api/

**Comment by thomcc** [comment]
That's fixed in SQLite 3.39.2, and we've already cut a release of libsqlite3-sys that includes that: https://github.com/rusqlite/rusqlite/releases/tag/sys0.25.1. This was done right away since the corresponding SQLite release said that it was a security fix that people should apply.

We should probably cut a rusqlite release in the near future, but it's not a security concern.

**Comment by thomcc** [comment]
If you would like to ensure your Cargo.lock includes that change, `cargo update -p libsqlite3-sys --precise 0.25.1` will do it. "Unlocked" build will always include the newer version.

**Comment by gwenn** [comment]
`rusqlite` doesn't seem to use `printf` except in some tests [here](https://github.com/rusqlite/rusqlite/blob/master/src/statement.rs#L1319-L1352).

**Comment by huitseeker** [comment]
Ah, yes, my bad, I mixed up the tag pointers between rusqlite and libsqlite-sys. Thanks for the correction, this seems to be inapplicable.
Here's a permalink that might help someone following in my footsteps:
https://github.com/rusqlite/rusqlite/blob/sys0.25.1/libsqlite3-sys/sqlite3/bindgen_bundled_version.rs#L3

**Comment by thomcc** [comment]
> rusqlite doesn't seem to use printf except in some tests [here](https://github.com/rusqlite/rusqlite/blob/master/src/statement.rs?rgh-link-date=2022-10-26T17%3A17%3A49Z#L1319-L1352).

It's still exposed via the SQL `format`/`printf` functions, I think (I guess I don't know if that's relevant for the exploit, though).

**Comment by thomcc** [comment]
This made me double-check if we had released a version of libsqlite3-sys that included a bundled SQLcipher with the fix for that CVE. We had not, but now have: https://github.com/rusqlite/rusqlite/releases/tag/sys0.25.2

In order to make the fix more widely usable, I've backported it to the 0.25.2 line, rather than cutting a semver-breaking 0.26.0 change.

**Comment by thomcc** [comment]
Note that I'm still not sure if rusqlite users are exposed to this -- it *looks* like we aren't since AFAICT the exploit does not impact the SQL api. I would still recommend folks update as a precaution, though.
