### ISSUE TITLE
Expose sqlite3_context_db_handle

### ISSUE THREAD

**Issue by phiresky** [rusqlite/rusqlite#643]
Within a user-defined function, it's possible to get the handle of the DB using sqlite3_context_db_handle. This is not possible from rusqlite currently. This is useful when the function is not defined as a lambda, because then it doesn't have access to the closure where the db connection is probably defined. I need this specifically when creating a sqlite extension (#631), though I'm sure it's useful elsewhere.

Here's an implementation that seems to be working, though I'm not sure if it's sound (are multiple Connection objects for one *mut sqlite3_handle valid?)

https://github.com/jgallagher/rusqlite/blob/022266239233857faa7f0b415c1a3d5095d96a53/src/functions.rs#L124

```rust
    pub fn get_connection(&self) -> Result<Connection> {
        let handle = unsafe { ffi::sqlite3_context_db_handle(self.ctx) };
        unsafe { Connection::from_handle(handle) }
    }
```

**Comment by thomcc** [comment]
> (are multiple Connection objects for one *mut sqlite3_handle valid?)

I don't think so, I'm pretty sure it has to be owning.

**Comment by gwenn** [comment]
I guess it is OK only a `Connection` reference is returned bound to `Context` lifetime.
And `Connection::from_handle` allocates its own statement cache which may be useless.

**Comment by phiresky** [comment]
A reference that only lives for the duration of the callback is fine. Though in my case I'm starting a transaction within the user-defined-function, and `conn.transaction()` requires a mutable reference to the connection..

**Comment by gwenn** [comment]
Would you mind sending a PR ?

**Comment by phiresky** [comment]
Sure, I have the code I'm currently using here: https://github.com/phiresky/rusqlite/commits/pr/loadable-extensions but

1. it's based on the loadable extensions pr (could be rebased I guess)
2. I'm not sure how to do it without using Connection::from_handle (because of the problem you mentioned above) and also how to return a mutable reference correctly (is that even possible without breaking mutable reference assumptions? Never really used ffi)

**Comment by thomcc** [comment]
> I guess it is OK if only a Connection reference is returned, bound to Context lifetime.

I don't know for sure if this is valid or not. It's tricky. You mean something like:

```rust
pub struct ConnectionRef<'ctx> {
	// comes from Connection::from_handle(sqlite3_context_db_handle(...))
    // and is non-owning
    conn: Connection,
    phantom: PhantomData<&'ctx Context<'ctx>>,
}
```

So long as this only implements `Deref`, I think this would prevent most issues. If it had `DerefMut` or otherwise exposed a `&mut Connection`, you could move it out of the mutable reference (mem::replace it with an in-memory connection or w/e) and then you'd have all kinds of problems, and could use it after the original one has been closed/freed.

But that's easy to avoid -- don't impl DerefMut. My concern about Send/Sync: we now have two `Connections`, the original, and this one (which behaves as a `&Connection` more or less). The original connection is `Send`, and even though this one isn't (if it were it would be definitely unsound, but easy to fix), my fear is that there isn't anything preventing the original connection from being accessed from another thread while this lives.

That is, is there any case where a user defined function is not triggered by a call to a function either on `&Connection` or on `&Statement` (which holds a `&Connection`)?

Or any other case we have to worry about along those lines?

P.S. @phiresky `unchecked_transaction` is avaliable in newer rusqlite releases which allows you to get transaction on a &Connection. Nesting them just causes a `Err`.

**Comment by phiresky** [comment]
@thomcc thanks! But I'm developing a sqlite extension using https://github.com/rusqlite/rusqlite/pull/631, which doesn't appear to have `unchecked_transaction` and has conflicts with current master, so I can't yet use it.

**Comment by phiresky** [comment]
I have opened a PR to address this here: #867
