### ISSUE TITLE
Can't use 'group' as a field name

### ISSUE THREAD

**Issue by jmrepetti** [rusqlite/rusqlite#723]
OSX
rustc 1.42.0 (b8cedc004 2020-03-09)
cargo 1.42.0 (86334295e 2020-01-31)

Hello! I'm having a problem when trying to use 'group' as a name of a field. 

Here's the error message:

```
Error: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("near \"group\": syntax error"))
```

And here's an example (can't make it work with the params! macro from the README example)

```rust
use rusqlite::{NO_PARAMS, Connection, Result};

fn main() -> Result<()> {
    let conn = Connection::open_in_memory()?;

    conn.execute(
        "CREATE TABLE person (
                  id              INTEGER PRIMARY KEY,
                  group           TEXT NOT NULL,
                  data            BLOB
                  )",
        NO_PARAMS,
    )?;

    Ok(())
}
```

I tried to escape the field, but then I'm having problem on the SELECTs.

**Comment by linacambridge** [comment]
Hi, thanks for the report! `GROUP` is a [keyword](https://www.sqlite.org/lang_keywords.html) in SQL, so you can't use it as a bare identifier without escaping:

```sql
CREATE TABLE person(
  id INTEGER PRIMARY KEY,
  "group" TEXT NOT NULL,
  data BLOB
);

INSERT INTO person(id, "group") VALUES(1, 'abc123');

SELECT id, "group" FROM person;

SELECT id FROM person WHERE "group" = 'abc123';
```

You can also use backticks (\`group\`) or square brackets (`[group]`) instead of `"group"`; SQLite supports all three escaping forms. In general, though, using a keyword for a column or table name is pretty clunky, because you need to escape it everywhere.

**Comment by jmrepetti** [comment]
Thanks for your answer, I’ll check how I build the SQL statement query string in my project. I’m probably escaping incorrectly.
