### ISSUE TITLE
Rusqlite need a community.

### ISSUE THREAD

**Issue by Voodlaz** [rusqlite/rusqlite#738]
Rusqlite need an Riot(IRC)/Discord/gitter/etc. community where people can ask questions and discuss rusqlite.

**Comment by thomcc** [comment]
I'm not opposed to it. I'm active on some of the rust discord channels, and mozilla riot (altho the latter mostly for work, and on the weekends I generally don't sign in there).

Gitter is probably the easiest for others though.

@gwenn do you have any thoughts here?

**Comment by gwenn** [comment]
Sorry, I have only restricted access to internet where I work.
And I am not active on any of them at home.
So I don't have any opinion.

**Comment by thomcc** [comment]
I've made https://gitter.im/rusqlite/community. I chose gitter just because it doesn't require anybody create another account for a thing, e.g. it uses github oauth.

Maybe it can help coordinate things, or something. Or at least reduce the number of issues we get that are actually about how to use rust or sqlite.

I'll add it to the readme later tonight.

**Comment by Voodlaz** [comment]
I made a pull request adding gitter chat badge to readme.
