### ISSUE TITLE
Update docs for order by _ desc

### ISSUE THREAD

**Issue by dessalines** [rusqlite/rusqlite#762]
I just wasted about 3 hours trying to figure out how to get prepared statements working with order by published desc;

If you try to do this, your prepared statement will fail. Your order by cannot be a param, and you cannot use the term desc, instead having to use `-`

IE : 

`let stmt_str = "select * from bleh order by -published limit ?1, ?2";` 

This needs to be in the docs somewhere so someone doesn't go through what I did.

**Comment by thomcc** [comment]
I'm sorry to hear you had the trouble, but this is something of a misunderstanding of the SQL language's semantics, specifically how names are distinguished from values.

The point of bound parameters is that no matter what values a user passes in, it's always treated as that value, even if that value happens to be, for example, a string with the same name as one of the columns in the table being queried.

That is, if it *didn't* work like this, and worked as you describe (where bound parameters were allowed to expand to column names) and you ran a query with `SELECT * FROM stuff WHERE user_name = ?1`, and then a user who has a user name of "user_name" comes along -- it would expand to `SELECT * FROM stuff WHERE user_name = user_name` which would suddenly produce all rows, instead of just the rows with the correct user name. Thankfully, databases don't do this, which is one of the reasons bound parameters are more secure and less error prone.

I hope that helps some, but if not, just remember that you can't use bound parameters to expand to table names, column names, or any pieces of SQL syntax. This is their purpose, even if it feels gross/risky to `format!` stuff into a SQL query.

---

All that said, I don't really want to be responsible for making rusqlite's documentation a SQL tutorial. That's way too big of a task and it's really not a good place for it. I am sorry you had trouble there, but I don't think there's anything we're able to do here.

In the future, SQLites website has good docs, which do document this https://www.sqlite.org/lang_expr.html and https://www.sqlite.org/lang_select.html#the_order_by_clause... But it looks like this doc would probably be confusing if you didn't already know what "evaluated" means here, and what kinds of things expression evaluation can produce in SQL.

**Comment by dessalines** [comment]
rusqlite's `order by _ desc` did not work, whereas other systems of prepared statements (even when not using that as params), works well.

**Comment by thomcc** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c513a9ecc7785c2b85be3d2015dc6ebb
