### ISSUE TITLE
Consider removing TravisCI

### ISSUE THREAD

**Issue by thomcc** [rusqlite/rusqlite#851]
Travis is much much slower than Github Actions. Anything we still have as travis we should move to GHA, and then we should remove Travis.

**Comment by striezel** [comment]
Travis CI builds are slower (to start) than GitHub Actions indeed.

However, Travis CI also allows to build on a Linux using ARM64 architecture, and it can perform builds on MacOS, too. I do not know whether this is something that is desired for rusqlite, but I have not yet seen that this is possible with GitHub Actions. In my experience, the ARM builds also start way faster than the usual amd64 builds - probably because most people do not care to build with ARM and the build queue on Travis CI is way shorter for ARM.

**Comment by thomcc** [comment]
We test on macos, windows, and linux on GHA. GHA can't test on native aarch64, but you can via `cross` on it.

See https://shift.click/blog/github-actions-rust/#run-tests-on-arm-mips--using-cross, or as a concrete example: https://github.com/thomcc/arcstr/blob/main/.github/workflows/ci.yml#L37-L44

That said, for rusqlite this isn't that valuable, so I haven't bothered to set it up.

**Comment by thomcc** [comment]
Done in #894.
