### ISSUE TITLE
csvtab is slow, specifically inner joins

### ISSUE THREAD

**Issue by alexjago** [rusqlite/rusqlite#852]
Hi - 

Queries on views involving inner joins are quite slow. This seems to scale with the number of rows involved. 

Please refer to https://github.com/alexjago/rusqlite-csvtab-slow for an example.

**Comment by gwenn** [comment]
I am afraid your are not comparing the same thing.
Because the `import` command create a table (not a virtual table).
So you are  comparing memory access vs disk access.
You should do `CREATE TABLE my_memory_table AS SELECT * FOM my_csv_virtual_table; -- ...` and `CREATE VIEW my_view AS SELECT ... FROM my_memory_table`.

**Comment by gwenn** [comment]
See [.import](https://github.com/sqlite/sqlite/blob/master/src/shell.c.in#L8240) code...

**Comment by alexjago** [comment]
Excellent! That's a much easier fix. 

Please consider adding a note on this to the documentation :)
