### ISSUE TITLE
Seperate Types submodule into own crate

### ISSUE THREAD

**Issue by Progdrasil** [rusqlite/rusqlite#941]
Similarly to [`postgres-types`](https://docs.rs/postgres-types/0.2.1/postgres_types/) which is part of the [`rust-postgres`](https://github.com/sfackler/rust-postgres) crate bundle. This would allow to just have the types as a dependency, namely the `ToSql` Trait. This would for example help in making a query builder crate such as [`sea-query`](https://github.com/SeaQL/sea-query). Adding all of rusqlite would be too much. See https://github.com/SeaQL/sea-query/issues/15.

**Comment by thomcc** [comment]
Hmm, not really sure I follow. In what situation would someone want to depend on rusqlite-types when they don't want to depend on rusqlite itself.

That is, if they do want to depend on rusqlite, then the whole dependency makes sense.

If they don't, then even the rusqlite-types dependency is pointless and should be behind a cargo feature.

Putting things in a separate crate is somewhat limiting, as it means we have to worry about the orphan rule/coherence more.

**Comment by Progdrasil** [comment]
The idea is to not require the entirety of rusqlite with all the batteries included and need to deal with all the other features that are not type specific that it provides. With the old cargo feature resolver this is less of an issue, but with the [new feature resolver](https://github.com/rust-lang/rfcs/pull/2957) this can become quite the head ache and lead to binary bloat.

Not only that but having the types module into its own crate can speed up incremental compilation since it will be its own compilation unit.

While I agree that they will eventually need to depend on the full rusqlite crate at one point in the chain, this reduces the size of dependencies that only really need the `ToSql` trait.

Regarding the orphan rule, I completely understand, however from #942 it seems already really well isolated.

**Comment by thomcc** [comment]
Hmm, my experience with the new feature resolver is that it leads to *less* bloat, so I'm confused by your assertion there.

It may speed up incremental compilation slightly, but total compilation time scales with the size of your dependency graph more than the size of the code in it, so I'm not sure I consider that especially convincing.

**Comment by Progdrasil** [comment]
I would have though having duplicates of the same dependency with different features would lead to more bloat.

**Comment by thomcc** [comment]
I missed this comment.

> I would have though having duplicates of the same dependency with different features would lead to more bloat.

Features are still unified. You won't have two copies of the same crate with different features in your crate graph (unless they're different semver versions, which doesn't really apply to rusqlite because of linking with sqlite).

The difference is that now if you have a feature turned on by a build-dependency, it won't be turned on for the runtime dependency.

---

That being said, I think I've softened on this a lot.

The biggest benefit to me is that `rusqlite-types` would likely be more semver-stable than `rusqlite`. Unfortunately, taking advantage of this has a downside in that it might confuse if `rusqlite-types` and `rusqlite` versions aren't always the same, but since most users would just access `-types` via `rusqlite::types`, it's hopefully fine.

That said, I think it probably needs slightly more considered handling than including just being the `types` module (Or maybe not — I'd like to give it more thought though). For example, it's possible that the types in `params.rs` should be included in it too... (Or maybe they shouldn't? It's hard for me to say...)

I'll think about this a bit more, though.

**Comment by mqudsi** [comment]
I agree about the dangers of mismatched versions of `rusqlite-types` and `rusqlite` - it's a real problem with some popular crates after a few breaking semver releases. 

You could do this in one crate with feature resolution, but it would be the opposite. A crate could include `rusqlite = { Version = ..., default-features = false }` to nuke its transitive dependencies and runtime logic (it would be up to that crate to decide if it still wants to place the rusqlite dependency behind a feature gate or not); in rusqlite, a default-enabled feature (`basic`) would enable all the current code and bring in all the current dependencies.

**Comment by thomcc** [comment]
Yeah, I don't think there's a reason to do this in one crate with feature resolution? What would the benefit be? I also think the request was brought by a misunderstanding of how resolver=2 functions.

Given that, I think I'm going to close this.
